
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: playground
  description: A workflow for onboarding applications to OCP cluster
  annotations:
    backstage.io/kubernetes-label-selector: 'app=playground'
    backstage.io/kubernetes-namespace: sonataflow-infra
    janus-idp.io/tekton: playground
    backstage.io/kubernetes-id: playground
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: test-workflows/playground
spec:
  type: workflow-project
  system: system:default/janus-orchestrator
  lifecycle: development
  owner: user:guest
